CREATE DATABASE GROUP8_SQL default character set utf8mb4 collate 'utf8mb4_unicode_ci';
USE GROUP8_SQL;

CREATE TABLE STAFF(
    	EMPLOYEE_ID INT auto_increment,
	FULL_NAME VARCHAR(100),
	USER_NAME VARCHAR(100),	
    	PASSWORD VARCHAR(50),
    	BIRTH_DAY DATE,
    	EMAIL VARCHAR(100),
    	IMAGE VARCHAR(100),
    	POSITION VARCHAR(50),
    	ROLL VARCHAR(10),
    	PRIMARY KEY(EMPLOYEE_ID)
    
);

ALTER TABLE STAFF ADD DELETE_FLAG varchar(5);